version: '3.7'

networks:
  vsu-schedule-network:
    name: vsu-schedule-network
    driver: bridge


services:
  schedule-service:
    image: schedule-service:latest
    build:
      context: ./schedule-service
    ports:
      - '9898:9898'
    networks:
      - vsu-schedule-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/schedule-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy

  telegram-service-rust:
    image: telegram-service-rust:latest
    build:
      context: ./telegram-service-rust
    networks:
      - vsu-schedule-network
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://admin:admin@students-db:5432/students-db
      - RUST_LOG=info
    depends_on:
      students-db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init-scripts-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: schedule-db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - vsu-schedule-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d schedule-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  students-db:
    container_name: students-db
    image: postgres
    ports:
      - '5434:5432'
    volumes:
      - ./init-scripts-students:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: students-db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - vsu-schedule-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d students-db"]
      interval: 5s
      timeout: 5s
      retries: 10
