version: '3.7'

networks:
  vsu-schedule-network:
    name: vsu-schedule-network
    driver: bridge


services:
  schedule-service:
    image: schedule-service:latest
    ports:
      - '9898:9898'
    networks:
      - vsu-schedule-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/schedule-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init-scripts-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - vsu-schedule-network

